### ISSUE TITLE
Milestone 2.1: Terraform execution, parsing .tfplan & .tfstate, save to DB

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#9]
@eistrati commented on [Thu Nov 09 2017](https://github.com/MitocGroup/cloudnativeci/issues/3)

---

@ddimitrioglo commented on [Wed Apr 04 2018](https://github.com/MitocGroup/cloudnativeci/issues/3#issuecomment-370410180)

**Workflow**:

1. `terraform plan`
2. `/cnci/plan/parse` (w/ stdout of cmd 1.)
3. Run tests
4. `terraform apply`
5. `/cnci/state/parse` (w/ .tfstate)`
6. Run tests
7. `terraform destroy`
8. `/cnci/state/parse` (w/ .tfstate)`
9. Run tests
10. Push CI logs to S3

**Subtasks**:
- [x] Implement `recink-cnci` component (for p.10)
- [x] Add endpoints:
  -  [x] `/cnci/plan/parse`
  - [x] `/cnci/state/parse`
- [x]  Research plan parser library
- [x] Implement plan-parse Lambda
- [x] Implement state-parse Lambda
- [x] Create tables for storing metadata
- [x] Save plan/state resources
- [x] Get parsed data before test-run (during `recink run terraform`)

---

@avozicov commented on [Tue Apr 17 2018](https://github.com/MitocGroup/cloudnativeci/issues/3#issuecomment-382005120)

Looks like we have an issue with saving **Plan** data to DynamoDB table
I have configured terraform component in .recink.yml for the microtype ec2 instance as follows:
- plan: true
- apply: true

While executing `recink run terraform -c cnci` command I got **apply** data is saved to DynamoDB but missed the **plan** data 

Please refer to attachment for more details:
- plan data is configured in .recink.yml
- plan data is returned in cli
- plan data is not saved in DynamoDb

<img width="279" alt="screen shot 2018-04-17 at 17 04 24" src="https://user-images.githubusercontent.com/12330493/38874747-82a680aa-4261-11e8-80ed-b8516a6ed411.png">

Only apply data is available in Deep[Dev]Resources table
<img width="1174" alt="screen shot 2018-04-17 at 15 47 25" src="https://user-images.githubusercontent.com/12330493/38874783-9bb26348-4261-11e8-9343-ac0f8e390aa6.png">
